### PR TITLE
Use the sdk/request module if we are in an sdk add-on

### PR DESCRIPTION
**Pull request by fzzzy**

### CODE REVIEW

**Comment by fzzzy** [comment]
I haven't tested this yet, but I think it is the right thing. How can I test it? I think min-vid is an sdk add-on that uses testpilot-metrics?

**Comment by jaredhirsch** [comment]
@fzzzy You can test using the SDK example addon in the examples directory, but this looks correct to me. I'll make you a collaborator, and you can merge after you test it.

As we discussed in #testpilot on IRC, this is good to land, and we can rip out bootstrapped support (and both sendBeacon and fetch, and Services.jsm I think) in a followup PR.

**Comment by jaredhirsch** [comment]
@fzzzy Ah, looks like the test pilot dev team already has admin rights over this repo.

One thing, you should bump the version number in this PR, and `npm publish` the updated version after you land the change.

**Comment by fzzzy** [comment]
Ok, I tested this with the example and it appears to work properly. I was unable to make the "may be causing Firefox to run slowly" error occur with the old version that used the hiddenWindow, but maybe that only happens if CPOWs are used a bunch of times.

**Pull request merged**
